config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'
  root 'questions#index'
  resources :questions do
    resources :answers, only: [:new, :create, :show, :update]
  end


  get "/auth/:provider/callback", to: "sessions#create"
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
belongs_to :question
belongs_to :user

validates :description, length: { minimum: 50 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
belongs_to :user
has_many :answers
validates :title, length: { minimum: 20 }
validates :description, length: { minimum: 50 }
# validates :user_id, presence: { message: "Please sign in to ask a question." }

end

app/models/user.rb
class User < ApplicationRecord
has_many :questions
has_many :answers

def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.uid = auth.uid
      user.provider = auth.provider
      user.avatar_url = auth.info.image
      user.username = auth.info.name
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.update_attributes(
      {
        user_id: session[:user_id]
      }
    )
    @answer.question = @question
    if @answer.save
      redirect_to @question, notice: 'Your answer has been posted successfully.'
    else
      @question = Question.find_by(id: params[:question_id])
      @answers = Question.find_by(id: params[:question_id]).answers.order('created_at desc')
      render :'questions/show'
    end
  end


  def update
    if !Answer.find_by(best_answer: true).nil?
      false_attributes =
        {
          best_answer: false
        }
      Answer.find_by(best_answer: true).update_attributes(false_attributes)
    end
    true_attributes =
      {
        best_answer: true
      }
    Answer.find_by(id: params[:id]).update_attributes(true_attributes)
    redirect_to question_path(params[:question_id])
  end

  private
    def answer_params
      params.require(:answer).permit(:question_id, :user_id, :description)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order('created_at desc')
  end

  def show
    @question = Question.find_by(id: params[:id])
    # why doesn't @question.answers work?
    @answers = Question.find_by(id: params[:id]).answers.order('created_at desc')
    @answer = Answer.new
    if !current_user.nil?
      @edit = true if current_user.id == @question.user_id
      @can_answer = true if !current_user.id.nil? && current_user.id != @question.user_id
    end
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    @question = Question.find_by(id: params[:id])
    if current_user.id == @question.user_id
      @question.update_attributes(question_params)
      redirect_to @question, notice: "Your question has been updated."
    else
      redirect_to @question, notice: "You cannot update a question that is not yours."
    end
  end

  def create
    @question = Question.new(question_params)
    @question.update_attributes(
      {
        user_id: session[:user_id]
      }
    )
    if @question.save
      redirect_to @question, notice: 'Your question has been posted successfully.'
    else
      render :new
    end
  end

  def destroy
    Question.find_by(id: params[:id]).delete
    Answer.where(question_id: params[:id]).delete_all

    redirect_to questions_index_path, notice: 'Your question has been deleted.'
  end

  private
    def question_params
      params.require(:question).permit(:title, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_omniauth(env["omniauth.auth"])

    if user.valid?
      session[:user_id] = user.id
      redirect_to request.env['omniauth.origin']
    end
  end

  def destroy
    reset_session
    redirect_to request.referer, notice: 'You have been signed out.'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/answers/_form.html.erb
<%= form_for [question, answer] do |f| %>
  <div class="field">
    <%= f.label :answer %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Answer Question" %>
  </div>
<% end %>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <% if current_user.blank? %>
          <%= link_to 'Sign In with Github', '/auth/github' %>
      <% else %>
        <p>You are signed in as <%= current_user.username %></p>
        <%= button_to "Sign Out", signout_path, method: :delete %>
      <% end %>
      <p id="notice"><%= notice %></p>
    </header>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', question_path %> | 
<%= link_to 'Home', questions_path %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<table>
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.title, question %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<h1>Question: <%= @question.title %></h1>
<% if @edit %>
  <%= link_to 'Edit Question', edit_question_path(@question) %> |
  <%= link_to 'Delete Question', @question, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<p>Asked by: <%= @question.user.username %></p>
<p>Description: <%= @question.description %></p>
<% if @answer.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if @can_answer %>
  <%= render 'answers/form', question: @question, answer: @answer %>
<% end %>
<% if @answers.any? %>
  <h2>Answers:</h2>
  <ul>
    <% @answers.each do |answer| %>
      <li><%= answer.description %>
        <% if answer.best_answer == true %>
          | Best Answer
        <% elsif @edit %>
          | <%= link_to 'Mark as Best', question_answer_path(@question, answer), method: :patch %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
<%= link_to "Home", questions_path %>